apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: audit
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
  containers:
  - name: nginx
    image: "gcr.io/openshift-sa-gcp/nginx:latest"
    ports:
    - containerPort: 80
